#pragma once

#include <tgbm/api/methods/getUpdates.hpp>
#include <tgbm/api/methods/setWebhook.hpp>
#include <tgbm/api/methods/deleteWebhook.hpp>
#include <tgbm/api/methods/getWebhookInfo.hpp>
#include <tgbm/api/methods/getMe.hpp>
#include <tgbm/api/methods/logOut.hpp>
#include <tgbm/api/methods/close.hpp>
#include <tgbm/api/methods/sendMessage.hpp>
#include <tgbm/api/methods/forwardMessage.hpp>
#include <tgbm/api/methods/forwardMessages.hpp>
#include <tgbm/api/methods/copyMessage.hpp>
#include <tgbm/api/methods/copyMessages.hpp>
#include <tgbm/api/methods/sendPhoto.hpp>
#include <tgbm/api/methods/sendAudio.hpp>
#include <tgbm/api/methods/sendDocument.hpp>
#include <tgbm/api/methods/sendVideo.hpp>
#include <tgbm/api/methods/sendAnimation.hpp>
#include <tgbm/api/methods/sendVoice.hpp>
#include <tgbm/api/methods/sendVideoNote.hpp>
#include <tgbm/api/methods/sendPaidMedia.hpp>
#include <tgbm/api/methods/sendMediaGroup.hpp>
#include <tgbm/api/methods/sendLocation.hpp>
#include <tgbm/api/methods/sendVenue.hpp>
#include <tgbm/api/methods/sendContact.hpp>
#include <tgbm/api/methods/sendPoll.hpp>
#include <tgbm/api/methods/sendDice.hpp>
#include <tgbm/api/methods/sendChatAction.hpp>
#include <tgbm/api/methods/setMessageReaction.hpp>
#include <tgbm/api/methods/getUserProfilePhotos.hpp>
#include <tgbm/api/methods/setUserEmojiStatus.hpp>
#include <tgbm/api/methods/getFile.hpp>
#include <tgbm/api/methods/banChatMember.hpp>
#include <tgbm/api/methods/unbanChatMember.hpp>
#include <tgbm/api/methods/restrictChatMember.hpp>
#include <tgbm/api/methods/promoteChatMember.hpp>
#include <tgbm/api/methods/setChatAdministratorCustomTitle.hpp>
#include <tgbm/api/methods/banChatSenderChat.hpp>
#include <tgbm/api/methods/unbanChatSenderChat.hpp>
#include <tgbm/api/methods/setChatPermissions.hpp>
#include <tgbm/api/methods/exportChatInviteLink.hpp>
#include <tgbm/api/methods/createChatInviteLink.hpp>
#include <tgbm/api/methods/editChatInviteLink.hpp>
#include <tgbm/api/methods/createChatSubscriptionInviteLink.hpp>
#include <tgbm/api/methods/editChatSubscriptionInviteLink.hpp>
#include <tgbm/api/methods/revokeChatInviteLink.hpp>
#include <tgbm/api/methods/approveChatJoinRequest.hpp>
#include <tgbm/api/methods/declineChatJoinRequest.hpp>
#include <tgbm/api/methods/setChatPhoto.hpp>
#include <tgbm/api/methods/deleteChatPhoto.hpp>
#include <tgbm/api/methods/setChatTitle.hpp>
#include <tgbm/api/methods/setChatDescription.hpp>
#include <tgbm/api/methods/pinChatMessage.hpp>
#include <tgbm/api/methods/unpinChatMessage.hpp>
#include <tgbm/api/methods/unpinAllChatMessages.hpp>
#include <tgbm/api/methods/leaveChat.hpp>
#include <tgbm/api/methods/getChat.hpp>
#include <tgbm/api/methods/getChatAdministrators.hpp>
#include <tgbm/api/methods/getChatMemberCount.hpp>
#include <tgbm/api/methods/getChatMember.hpp>
#include <tgbm/api/methods/setChatStickerSet.hpp>
#include <tgbm/api/methods/deleteChatStickerSet.hpp>
#include <tgbm/api/methods/getForumTopicIconStickers.hpp>
#include <tgbm/api/methods/createForumTopic.hpp>
#include <tgbm/api/methods/editForumTopic.hpp>
#include <tgbm/api/methods/closeForumTopic.hpp>
#include <tgbm/api/methods/reopenForumTopic.hpp>
#include <tgbm/api/methods/deleteForumTopic.hpp>
#include <tgbm/api/methods/unpinAllForumTopicMessages.hpp>
#include <tgbm/api/methods/editGeneralForumTopic.hpp>
#include <tgbm/api/methods/closeGeneralForumTopic.hpp>
#include <tgbm/api/methods/reopenGeneralForumTopic.hpp>
#include <tgbm/api/methods/hideGeneralForumTopic.hpp>
#include <tgbm/api/methods/unhideGeneralForumTopic.hpp>
#include <tgbm/api/methods/unpinAllGeneralForumTopicMessages.hpp>
#include <tgbm/api/methods/answerCallbackQuery.hpp>
#include <tgbm/api/methods/getUserChatBoosts.hpp>
#include <tgbm/api/methods/getBusinessConnection.hpp>
#include <tgbm/api/methods/setMyCommands.hpp>
#include <tgbm/api/methods/deleteMyCommands.hpp>
#include <tgbm/api/methods/getMyCommands.hpp>
#include <tgbm/api/methods/setMyName.hpp>
#include <tgbm/api/methods/getMyName.hpp>
#include <tgbm/api/methods/setMyDescription.hpp>
#include <tgbm/api/methods/getMyDescription.hpp>
#include <tgbm/api/methods/setMyShortDescription.hpp>
#include <tgbm/api/methods/getMyShortDescription.hpp>
#include <tgbm/api/methods/setChatMenuButton.hpp>
#include <tgbm/api/methods/getChatMenuButton.hpp>
#include <tgbm/api/methods/setMyDefaultAdministratorRights.hpp>
#include <tgbm/api/methods/getMyDefaultAdministratorRights.hpp>
#include <tgbm/api/methods/editMessageText.hpp>
#include <tgbm/api/methods/editMessageCaption.hpp>
#include <tgbm/api/methods/editMessageMedia.hpp>
#include <tgbm/api/methods/editMessageLiveLocation.hpp>
#include <tgbm/api/methods/stopMessageLiveLocation.hpp>
#include <tgbm/api/methods/editMessageReplyMarkup.hpp>
#include <tgbm/api/methods/stopPoll.hpp>
#include <tgbm/api/methods/deleteMessage.hpp>
#include <tgbm/api/methods/deleteMessages.hpp>
#include <tgbm/api/methods/sendSticker.hpp>
#include <tgbm/api/methods/getStickerSet.hpp>
#include <tgbm/api/methods/getCustomEmojiStickers.hpp>
#include <tgbm/api/methods/uploadStickerFile.hpp>
#include <tgbm/api/methods/createNewStickerSet.hpp>
#include <tgbm/api/methods/addStickerToSet.hpp>
#include <tgbm/api/methods/setStickerPositionInSet.hpp>
#include <tgbm/api/methods/deleteStickerFromSet.hpp>
#include <tgbm/api/methods/replaceStickerInSet.hpp>
#include <tgbm/api/methods/setStickerEmojiList.hpp>
#include <tgbm/api/methods/setStickerKeywords.hpp>
#include <tgbm/api/methods/setStickerMaskPosition.hpp>
#include <tgbm/api/methods/setStickerSetTitle.hpp>
#include <tgbm/api/methods/setStickerSetThumbnail.hpp>
#include <tgbm/api/methods/setCustomEmojiStickerSetThumbnail.hpp>
#include <tgbm/api/methods/deleteStickerSet.hpp>
#include <tgbm/api/methods/getAvailableGifts.hpp>
#include <tgbm/api/methods/sendGift.hpp>
#include <tgbm/api/methods/answerInlineQuery.hpp>
#include <tgbm/api/methods/answerWebAppQuery.hpp>
#include <tgbm/api/methods/savePreparedInlineMessage.hpp>
#include <tgbm/api/methods/sendInvoice.hpp>
#include <tgbm/api/methods/createInvoiceLink.hpp>
#include <tgbm/api/methods/answerShippingQuery.hpp>
#include <tgbm/api/methods/answerPreCheckoutQuery.hpp>
#include <tgbm/api/methods/getStarTransactions.hpp>
#include <tgbm/api/methods/refundStarPayment.hpp>
#include <tgbm/api/methods/editUserStarSubscription.hpp>
#include <tgbm/api/methods/setPassportDataErrors.hpp>
#include <tgbm/api/methods/sendGame.hpp>
#include <tgbm/api/methods/setGameScore.hpp>
#include <tgbm/api/methods/getGameHighScores.hpp>
