#pragma once

#include <tgbm/api/types/Update.hpp>
#include <tgbm/api/types/WebhookInfo.hpp>
#include <tgbm/api/types/User.hpp>
#include <tgbm/api/types/Chat.hpp>
#include <tgbm/api/types/ChatFullInfo.hpp>
#include <tgbm/api/types/Message.hpp>
#include <tgbm/api/types/MessageId.hpp>
#include <tgbm/api/types/InaccessibleMessage.hpp>
#include <tgbm/api/types/MaybeInaccessibleMessage.hpp>
#include <tgbm/api/types/MessageEntity.hpp>
#include <tgbm/api/types/TextQuote.hpp>
#include <tgbm/api/types/ExternalReplyInfo.hpp>
#include <tgbm/api/types/ReplyParameters.hpp>
#include <tgbm/api/types/MessageOrigin.hpp>
#include <tgbm/api/types/MessageOriginUser.hpp>
#include <tgbm/api/types/MessageOriginHiddenUser.hpp>
#include <tgbm/api/types/MessageOriginChat.hpp>
#include <tgbm/api/types/MessageOriginChannel.hpp>
#include <tgbm/api/types/PhotoSize.hpp>
#include <tgbm/api/types/Animation.hpp>
#include <tgbm/api/types/Audio.hpp>
#include <tgbm/api/types/Document.hpp>
#include <tgbm/api/types/Story.hpp>
#include <tgbm/api/types/Video.hpp>
#include <tgbm/api/types/VideoNote.hpp>
#include <tgbm/api/types/Voice.hpp>
#include <tgbm/api/types/PaidMediaInfo.hpp>
#include <tgbm/api/types/PaidMedia.hpp>
#include <tgbm/api/types/PaidMediaPreview.hpp>
#include <tgbm/api/types/PaidMediaPhoto.hpp>
#include <tgbm/api/types/PaidMediaVideo.hpp>
#include <tgbm/api/types/Contact.hpp>
#include <tgbm/api/types/Dice.hpp>
#include <tgbm/api/types/PollOption.hpp>
#include <tgbm/api/types/InputPollOption.hpp>
#include <tgbm/api/types/PollAnswer.hpp>
#include <tgbm/api/types/Poll.hpp>
#include <tgbm/api/types/Location.hpp>
#include <tgbm/api/types/Venue.hpp>
#include <tgbm/api/types/WebAppData.hpp>
#include <tgbm/api/types/ProximityAlertTriggered.hpp>
#include <tgbm/api/types/MessageAutoDeleteTimerChanged.hpp>
#include <tgbm/api/types/ChatBoostAdded.hpp>
#include <tgbm/api/types/BackgroundFill.hpp>
#include <tgbm/api/types/BackgroundFillSolid.hpp>
#include <tgbm/api/types/BackgroundFillGradient.hpp>
#include <tgbm/api/types/BackgroundFillFreeformGradient.hpp>
#include <tgbm/api/types/BackgroundType.hpp>
#include <tgbm/api/types/BackgroundTypeFill.hpp>
#include <tgbm/api/types/BackgroundTypeWallpaper.hpp>
#include <tgbm/api/types/BackgroundTypePattern.hpp>
#include <tgbm/api/types/BackgroundTypeChatTheme.hpp>
#include <tgbm/api/types/ChatBackground.hpp>
#include <tgbm/api/types/ForumTopicCreated.hpp>
#include <tgbm/api/types/ForumTopicClosed.hpp>
#include <tgbm/api/types/ForumTopicEdited.hpp>
#include <tgbm/api/types/ForumTopicReopened.hpp>
#include <tgbm/api/types/GeneralForumTopicHidden.hpp>
#include <tgbm/api/types/GeneralForumTopicUnhidden.hpp>
#include <tgbm/api/types/SharedUser.hpp>
#include <tgbm/api/types/UsersShared.hpp>
#include <tgbm/api/types/ChatShared.hpp>
#include <tgbm/api/types/WriteAccessAllowed.hpp>
#include <tgbm/api/types/VideoChatScheduled.hpp>
#include <tgbm/api/types/VideoChatStarted.hpp>
#include <tgbm/api/types/VideoChatEnded.hpp>
#include <tgbm/api/types/VideoChatParticipantsInvited.hpp>
#include <tgbm/api/types/PaidMessagePriceChanged.hpp>
#include <tgbm/api/types/GiveawayCreated.hpp>
#include <tgbm/api/types/Giveaway.hpp>
#include <tgbm/api/types/GiveawayWinners.hpp>
#include <tgbm/api/types/GiveawayCompleted.hpp>
#include <tgbm/api/types/LinkPreviewOptions.hpp>
#include <tgbm/api/types/UserProfilePhotos.hpp>
#include <tgbm/api/types/File.hpp>
#include <tgbm/api/types/WebAppInfo.hpp>
#include <tgbm/api/types/ReplyKeyboardMarkup.hpp>
#include <tgbm/api/types/KeyboardButton.hpp>
#include <tgbm/api/types/KeyboardButtonRequestUsers.hpp>
#include <tgbm/api/types/KeyboardButtonRequestChat.hpp>
#include <tgbm/api/types/KeyboardButtonPollType.hpp>
#include <tgbm/api/types/ReplyKeyboardRemove.hpp>
#include <tgbm/api/types/InlineKeyboardMarkup.hpp>
#include <tgbm/api/types/InlineKeyboardButton.hpp>
#include <tgbm/api/types/LoginUrl.hpp>
#include <tgbm/api/types/SwitchInlineQueryChosenChat.hpp>
#include <tgbm/api/types/CopyTextButton.hpp>
#include <tgbm/api/types/CallbackQuery.hpp>
#include <tgbm/api/types/ForceReply.hpp>
#include <tgbm/api/types/ChatPhoto.hpp>
#include <tgbm/api/types/ChatInviteLink.hpp>
#include <tgbm/api/types/ChatAdministratorRights.hpp>
#include <tgbm/api/types/ChatMemberUpdated.hpp>
#include <tgbm/api/types/ChatMember.hpp>
#include <tgbm/api/types/ChatMemberOwner.hpp>
#include <tgbm/api/types/ChatMemberAdministrator.hpp>
#include <tgbm/api/types/ChatMemberMember.hpp>
#include <tgbm/api/types/ChatMemberRestricted.hpp>
#include <tgbm/api/types/ChatMemberLeft.hpp>
#include <tgbm/api/types/ChatMemberBanned.hpp>
#include <tgbm/api/types/ChatJoinRequest.hpp>
#include <tgbm/api/types/ChatPermissions.hpp>
#include <tgbm/api/types/Birthdate.hpp>
#include <tgbm/api/types/BusinessIntro.hpp>
#include <tgbm/api/types/BusinessLocation.hpp>
#include <tgbm/api/types/BusinessOpeningHoursInterval.hpp>
#include <tgbm/api/types/BusinessOpeningHours.hpp>
#include <tgbm/api/types/StoryAreaPosition.hpp>
#include <tgbm/api/types/LocationAddress.hpp>
#include <tgbm/api/types/StoryAreaType.hpp>
#include <tgbm/api/types/StoryAreaTypeLocation.hpp>
#include <tgbm/api/types/StoryAreaTypeSuggestedReaction.hpp>
#include <tgbm/api/types/StoryAreaTypeLink.hpp>
#include <tgbm/api/types/StoryAreaTypeWeather.hpp>
#include <tgbm/api/types/StoryAreaTypeUniqueGift.hpp>
#include <tgbm/api/types/StoryArea.hpp>
#include <tgbm/api/types/ChatLocation.hpp>
#include <tgbm/api/types/ReactionType.hpp>
#include <tgbm/api/types/ReactionTypeEmoji.hpp>
#include <tgbm/api/types/ReactionTypeCustomEmoji.hpp>
#include <tgbm/api/types/ReactionTypePaid.hpp>
#include <tgbm/api/types/ReactionCount.hpp>
#include <tgbm/api/types/MessageReactionUpdated.hpp>
#include <tgbm/api/types/MessageReactionCountUpdated.hpp>
#include <tgbm/api/types/ForumTopic.hpp>
#include <tgbm/api/types/Gift.hpp>
#include <tgbm/api/types/Gifts.hpp>
#include <tgbm/api/types/UniqueGiftModel.hpp>
#include <tgbm/api/types/UniqueGiftSymbol.hpp>
#include <tgbm/api/types/UniqueGiftBackdropColors.hpp>
#include <tgbm/api/types/UniqueGiftBackdrop.hpp>
#include <tgbm/api/types/UniqueGift.hpp>
#include <tgbm/api/types/GiftInfo.hpp>
#include <tgbm/api/types/UniqueGiftInfo.hpp>
#include <tgbm/api/types/OwnedGift.hpp>
#include <tgbm/api/types/OwnedGiftRegular.hpp>
#include <tgbm/api/types/OwnedGiftUnique.hpp>
#include <tgbm/api/types/OwnedGifts.hpp>
#include <tgbm/api/types/AcceptedGiftTypes.hpp>
#include <tgbm/api/types/StarAmount.hpp>
#include <tgbm/api/types/BotCommand.hpp>
#include <tgbm/api/types/BotCommandScope.hpp>
#include <tgbm/api/types/BotCommandScopeDefault.hpp>
#include <tgbm/api/types/BotCommandScopeAllPrivateChats.hpp>
#include <tgbm/api/types/BotCommandScopeAllGroupChats.hpp>
#include <tgbm/api/types/BotCommandScopeAllChatAdministrators.hpp>
#include <tgbm/api/types/BotCommandScopeChat.hpp>
#include <tgbm/api/types/BotCommandScopeChatAdministrators.hpp>
#include <tgbm/api/types/BotCommandScopeChatMember.hpp>
#include <tgbm/api/types/BotName.hpp>
#include <tgbm/api/types/BotDescription.hpp>
#include <tgbm/api/types/BotShortDescription.hpp>
#include <tgbm/api/types/MenuButton.hpp>
#include <tgbm/api/types/MenuButtonCommands.hpp>
#include <tgbm/api/types/MenuButtonWebApp.hpp>
#include <tgbm/api/types/MenuButtonDefault.hpp>
#include <tgbm/api/types/ChatBoostSource.hpp>
#include <tgbm/api/types/ChatBoostSourcePremium.hpp>
#include <tgbm/api/types/ChatBoostSourceGiftCode.hpp>
#include <tgbm/api/types/ChatBoostSourceGiveaway.hpp>
#include <tgbm/api/types/ChatBoost.hpp>
#include <tgbm/api/types/ChatBoostUpdated.hpp>
#include <tgbm/api/types/ChatBoostRemoved.hpp>
#include <tgbm/api/types/UserChatBoosts.hpp>
#include <tgbm/api/types/BusinessBotRights.hpp>
#include <tgbm/api/types/BusinessConnection.hpp>
#include <tgbm/api/types/BusinessMessagesDeleted.hpp>
#include <tgbm/api/types/ResponseParameters.hpp>
#include <tgbm/api/types/InputMedia.hpp>
#include <tgbm/api/types/InputMediaAnimation.hpp>
#include <tgbm/api/types/InputMediaDocument.hpp>
#include <tgbm/api/types/InputMediaAudio.hpp>
#include <tgbm/api/types/InputMediaPhoto.hpp>
#include <tgbm/api/types/InputMediaVideo.hpp>
#include <tgbm/api/types/InputFile.hpp>
#include <tgbm/api/types/InputPaidMedia.hpp>
#include <tgbm/api/types/InputPaidMediaPhoto.hpp>
#include <tgbm/api/types/InputPaidMediaVideo.hpp>
#include <tgbm/api/types/InputProfilePhoto.hpp>
#include <tgbm/api/types/InputProfilePhotoStatic.hpp>
#include <tgbm/api/types/InputProfilePhotoAnimated.hpp>
#include <tgbm/api/types/InputStoryContent.hpp>
#include <tgbm/api/types/InputStoryContentPhoto.hpp>
#include <tgbm/api/types/InputStoryContentVideo.hpp>
#include <tgbm/api/types/Sticker.hpp>
#include <tgbm/api/types/StickerSet.hpp>
#include <tgbm/api/types/MaskPosition.hpp>
#include <tgbm/api/types/InputSticker.hpp>
#include <tgbm/api/types/InlineQuery.hpp>
#include <tgbm/api/types/InlineQueryResultsButton.hpp>
#include <tgbm/api/types/InlineQueryResult.hpp>
#include <tgbm/api/types/InlineQueryResultCachedAudio.hpp>
#include <tgbm/api/types/InlineQueryResultCachedDocument.hpp>
#include <tgbm/api/types/InlineQueryResultCachedGif.hpp>
#include <tgbm/api/types/InlineQueryResultCachedMpeg4Gif.hpp>
#include <tgbm/api/types/InlineQueryResultCachedPhoto.hpp>
#include <tgbm/api/types/InlineQueryResultCachedSticker.hpp>
#include <tgbm/api/types/InlineQueryResultCachedVideo.hpp>
#include <tgbm/api/types/InlineQueryResultCachedVoice.hpp>
#include <tgbm/api/types/InlineQueryResultArticle.hpp>
#include <tgbm/api/types/InlineQueryResultAudio.hpp>
#include <tgbm/api/types/InlineQueryResultContact.hpp>
#include <tgbm/api/types/InlineQueryResultGame.hpp>
#include <tgbm/api/types/InlineQueryResultDocument.hpp>
#include <tgbm/api/types/InlineQueryResultGif.hpp>
#include <tgbm/api/types/InlineQueryResultLocation.hpp>
#include <tgbm/api/types/InlineQueryResultMpeg4Gif.hpp>
#include <tgbm/api/types/InlineQueryResultPhoto.hpp>
#include <tgbm/api/types/InlineQueryResultVenue.hpp>
#include <tgbm/api/types/InlineQueryResultVideo.hpp>
#include <tgbm/api/types/InlineQueryResultVoice.hpp>
#include <tgbm/api/types/InputMessageContent.hpp>
#include <tgbm/api/types/InputTextMessageContent.hpp>
#include <tgbm/api/types/InputLocationMessageContent.hpp>
#include <tgbm/api/types/InputVenueMessageContent.hpp>
#include <tgbm/api/types/InputContactMessageContent.hpp>
#include <tgbm/api/types/InputInvoiceMessageContent.hpp>
#include <tgbm/api/types/ChosenInlineResult.hpp>
#include <tgbm/api/types/SentWebAppMessage.hpp>
#include <tgbm/api/types/PreparedInlineMessage.hpp>
#include <tgbm/api/types/LabeledPrice.hpp>
#include <tgbm/api/types/Invoice.hpp>
#include <tgbm/api/types/ShippingAddress.hpp>
#include <tgbm/api/types/OrderInfo.hpp>
#include <tgbm/api/types/ShippingOption.hpp>
#include <tgbm/api/types/SuccessfulPayment.hpp>
#include <tgbm/api/types/RefundedPayment.hpp>
#include <tgbm/api/types/ShippingQuery.hpp>
#include <tgbm/api/types/PreCheckoutQuery.hpp>
#include <tgbm/api/types/PaidMediaPurchased.hpp>
#include <tgbm/api/types/RevenueWithdrawalState.hpp>
#include <tgbm/api/types/RevenueWithdrawalStatePending.hpp>
#include <tgbm/api/types/RevenueWithdrawalStateSucceeded.hpp>
#include <tgbm/api/types/RevenueWithdrawalStateFailed.hpp>
#include <tgbm/api/types/AffiliateInfo.hpp>
#include <tgbm/api/types/TransactionPartner.hpp>
#include <tgbm/api/types/TransactionPartnerUser.hpp>
#include <tgbm/api/types/TransactionPartnerChat.hpp>
#include <tgbm/api/types/TransactionPartnerAffiliateProgram.hpp>
#include <tgbm/api/types/TransactionPartnerFragment.hpp>
#include <tgbm/api/types/TransactionPartnerTelegramAds.hpp>
#include <tgbm/api/types/TransactionPartnerTelegramApi.hpp>
#include <tgbm/api/types/TransactionPartnerOther.hpp>
#include <tgbm/api/types/StarTransaction.hpp>
#include <tgbm/api/types/StarTransactions.hpp>
#include <tgbm/api/types/PassportData.hpp>
#include <tgbm/api/types/PassportFile.hpp>
#include <tgbm/api/types/EncryptedPassportElement.hpp>
#include <tgbm/api/types/EncryptedCredentials.hpp>
#include <tgbm/api/types/PassportElementError.hpp>
#include <tgbm/api/types/PassportElementErrorDataField.hpp>
#include <tgbm/api/types/PassportElementErrorFrontSide.hpp>
#include <tgbm/api/types/PassportElementErrorReverseSide.hpp>
#include <tgbm/api/types/PassportElementErrorSelfie.hpp>
#include <tgbm/api/types/PassportElementErrorFile.hpp>
#include <tgbm/api/types/PassportElementErrorFiles.hpp>
#include <tgbm/api/types/PassportElementErrorTranslationFile.hpp>
#include <tgbm/api/types/PassportElementErrorTranslationFiles.hpp>
#include <tgbm/api/types/PassportElementErrorUnspecified.hpp>
#include <tgbm/api/types/Game.hpp>
#include <tgbm/api/types/CallbackGame.hpp>
#include <tgbm/api/types/GameHighScore.hpp>
