#include <tgbm/api/types/all.hpp>
namespace tgbm::api {
bool Update::operator==(const Update&) const = default;
std::strong_ordering Update::operator<=>(const Update&) const = default;
bool WebhookInfo::operator==(const WebhookInfo&) const = default;
std::strong_ordering WebhookInfo::operator<=>(const WebhookInfo&) const = default;
bool User::operator==(const User&) const = default;
std::strong_ordering User::operator<=>(const User&) const = default;
bool Chat::operator==(const Chat&) const = default;
std::strong_ordering Chat::operator<=>(const Chat&) const = default;
bool ChatFullInfo::operator==(const ChatFullInfo&) const = default;
std::strong_ordering ChatFullInfo::operator<=>(const ChatFullInfo&) const = default;
bool Message::operator==(const Message&) const = default;
std::strong_ordering Message::operator<=>(const Message&) const = default;
bool MessageId::operator==(const MessageId&) const = default;
std::strong_ordering MessageId::operator<=>(const MessageId&) const = default;
bool InaccessibleMessage::operator==(const InaccessibleMessage&) const = default;
std::strong_ordering InaccessibleMessage::operator<=>(const InaccessibleMessage&) const = default;
bool MessageEntity::operator==(const MessageEntity&) const = default;
std::strong_ordering MessageEntity::operator<=>(const MessageEntity&) const = default;
bool TextQuote::operator==(const TextQuote&) const = default;
std::strong_ordering TextQuote::operator<=>(const TextQuote&) const = default;
bool ExternalReplyInfo::operator==(const ExternalReplyInfo&) const = default;
std::strong_ordering ExternalReplyInfo::operator<=>(const ExternalReplyInfo&) const = default;
bool ReplyParameters::operator==(const ReplyParameters&) const = default;
std::strong_ordering ReplyParameters::operator<=>(const ReplyParameters&) const = default;
bool PhotoSize::operator==(const PhotoSize&) const = default;
std::strong_ordering PhotoSize::operator<=>(const PhotoSize&) const = default;
bool Animation::operator==(const Animation&) const = default;
std::strong_ordering Animation::operator<=>(const Animation&) const = default;
bool Audio::operator==(const Audio&) const = default;
std::strong_ordering Audio::operator<=>(const Audio&) const = default;
bool Document::operator==(const Document&) const = default;
std::strong_ordering Document::operator<=>(const Document&) const = default;
bool Story::operator==(const Story&) const = default;
std::strong_ordering Story::operator<=>(const Story&) const = default;
bool Video::operator==(const Video&) const = default;
std::strong_ordering Video::operator<=>(const Video&) const = default;
bool VideoNote::operator==(const VideoNote&) const = default;
std::strong_ordering VideoNote::operator<=>(const VideoNote&) const = default;
bool Voice::operator==(const Voice&) const = default;
std::strong_ordering Voice::operator<=>(const Voice&) const = default;
bool PaidMediaInfo::operator==(const PaidMediaInfo&) const = default;
std::strong_ordering PaidMediaInfo::operator<=>(const PaidMediaInfo&) const = default;
bool Contact::operator==(const Contact&) const = default;
std::strong_ordering Contact::operator<=>(const Contact&) const = default;
bool Dice::operator==(const Dice&) const = default;
std::strong_ordering Dice::operator<=>(const Dice&) const = default;
bool PollOption::operator==(const PollOption&) const = default;
std::strong_ordering PollOption::operator<=>(const PollOption&) const = default;
bool InputPollOption::operator==(const InputPollOption&) const = default;
std::strong_ordering InputPollOption::operator<=>(const InputPollOption&) const = default;
bool PollAnswer::operator==(const PollAnswer&) const = default;
std::strong_ordering PollAnswer::operator<=>(const PollAnswer&) const = default;
bool Poll::operator==(const Poll&) const = default;
std::strong_ordering Poll::operator<=>(const Poll&) const = default;
bool ChecklistTask::operator==(const ChecklistTask&) const = default;
std::strong_ordering ChecklistTask::operator<=>(const ChecklistTask&) const = default;
bool Checklist::operator==(const Checklist&) const = default;
std::strong_ordering Checklist::operator<=>(const Checklist&) const = default;
bool InputChecklistTask::operator==(const InputChecklistTask&) const = default;
std::strong_ordering InputChecklistTask::operator<=>(const InputChecklistTask&) const = default;
bool InputChecklist::operator==(const InputChecklist&) const = default;
std::strong_ordering InputChecklist::operator<=>(const InputChecklist&) const = default;
bool ChecklistTasksDone::operator==(const ChecklistTasksDone&) const = default;
std::strong_ordering ChecklistTasksDone::operator<=>(const ChecklistTasksDone&) const = default;
bool ChecklistTasksAdded::operator==(const ChecklistTasksAdded&) const = default;
std::strong_ordering ChecklistTasksAdded::operator<=>(const ChecklistTasksAdded&) const = default;
bool Location::operator==(const Location&) const = default;
std::strong_ordering Location::operator<=>(const Location&) const = default;
bool Venue::operator==(const Venue&) const = default;
std::strong_ordering Venue::operator<=>(const Venue&) const = default;
bool WebAppData::operator==(const WebAppData&) const = default;
std::strong_ordering WebAppData::operator<=>(const WebAppData&) const = default;
bool ProximityAlertTriggered::operator==(const ProximityAlertTriggered&) const = default;
std::strong_ordering ProximityAlertTriggered::operator<=>(const ProximityAlertTriggered&) const = default;
bool MessageAutoDeleteTimerChanged::operator==(const MessageAutoDeleteTimerChanged&) const = default;
std::strong_ordering MessageAutoDeleteTimerChanged::operator<=>(const MessageAutoDeleteTimerChanged&) const =
    default;
bool ChatBoostAdded::operator==(const ChatBoostAdded&) const = default;
std::strong_ordering ChatBoostAdded::operator<=>(const ChatBoostAdded&) const = default;
bool ChatBackground::operator==(const ChatBackground&) const = default;
std::strong_ordering ChatBackground::operator<=>(const ChatBackground&) const = default;
bool ForumTopicCreated::operator==(const ForumTopicCreated&) const = default;
std::strong_ordering ForumTopicCreated::operator<=>(const ForumTopicCreated&) const = default;
bool ForumTopicClosed::operator==(const ForumTopicClosed&) const = default;
std::strong_ordering ForumTopicClosed::operator<=>(const ForumTopicClosed&) const = default;
bool ForumTopicEdited::operator==(const ForumTopicEdited&) const = default;
std::strong_ordering ForumTopicEdited::operator<=>(const ForumTopicEdited&) const = default;
bool ForumTopicReopened::operator==(const ForumTopicReopened&) const = default;
std::strong_ordering ForumTopicReopened::operator<=>(const ForumTopicReopened&) const = default;
bool GeneralForumTopicHidden::operator==(const GeneralForumTopicHidden&) const = default;
std::strong_ordering GeneralForumTopicHidden::operator<=>(const GeneralForumTopicHidden&) const = default;
bool GeneralForumTopicUnhidden::operator==(const GeneralForumTopicUnhidden&) const = default;
std::strong_ordering GeneralForumTopicUnhidden::operator<=>(const GeneralForumTopicUnhidden&) const = default;
bool SharedUser::operator==(const SharedUser&) const = default;
std::strong_ordering SharedUser::operator<=>(const SharedUser&) const = default;
bool UsersShared::operator==(const UsersShared&) const = default;
std::strong_ordering UsersShared::operator<=>(const UsersShared&) const = default;
bool ChatShared::operator==(const ChatShared&) const = default;
std::strong_ordering ChatShared::operator<=>(const ChatShared&) const = default;
bool WriteAccessAllowed::operator==(const WriteAccessAllowed&) const = default;
std::strong_ordering WriteAccessAllowed::operator<=>(const WriteAccessAllowed&) const = default;
bool VideoChatScheduled::operator==(const VideoChatScheduled&) const = default;
std::strong_ordering VideoChatScheduled::operator<=>(const VideoChatScheduled&) const = default;
bool VideoChatStarted::operator==(const VideoChatStarted&) const = default;
std::strong_ordering VideoChatStarted::operator<=>(const VideoChatStarted&) const = default;
bool VideoChatEnded::operator==(const VideoChatEnded&) const = default;
std::strong_ordering VideoChatEnded::operator<=>(const VideoChatEnded&) const = default;
bool VideoChatParticipantsInvited::operator==(const VideoChatParticipantsInvited&) const = default;
std::strong_ordering VideoChatParticipantsInvited::operator<=>(const VideoChatParticipantsInvited&) const =
    default;
bool PaidMessagePriceChanged::operator==(const PaidMessagePriceChanged&) const = default;
std::strong_ordering PaidMessagePriceChanged::operator<=>(const PaidMessagePriceChanged&) const = default;
bool DirectMessagePriceChanged::operator==(const DirectMessagePriceChanged&) const = default;
std::strong_ordering DirectMessagePriceChanged::operator<=>(const DirectMessagePriceChanged&) const = default;
bool SuggestedPostApproved::operator==(const SuggestedPostApproved&) const = default;
std::strong_ordering SuggestedPostApproved::operator<=>(const SuggestedPostApproved&) const = default;
bool SuggestedPostApprovalFailed::operator==(const SuggestedPostApprovalFailed&) const = default;
std::strong_ordering SuggestedPostApprovalFailed::operator<=>(const SuggestedPostApprovalFailed&) const =
    default;
bool SuggestedPostDeclined::operator==(const SuggestedPostDeclined&) const = default;
std::strong_ordering SuggestedPostDeclined::operator<=>(const SuggestedPostDeclined&) const = default;
bool SuggestedPostPaid::operator==(const SuggestedPostPaid&) const = default;
std::strong_ordering SuggestedPostPaid::operator<=>(const SuggestedPostPaid&) const = default;
bool SuggestedPostRefunded::operator==(const SuggestedPostRefunded&) const = default;
std::strong_ordering SuggestedPostRefunded::operator<=>(const SuggestedPostRefunded&) const = default;
bool GiveawayCreated::operator==(const GiveawayCreated&) const = default;
std::strong_ordering GiveawayCreated::operator<=>(const GiveawayCreated&) const = default;
bool Giveaway::operator==(const Giveaway&) const = default;
std::strong_ordering Giveaway::operator<=>(const Giveaway&) const = default;
bool GiveawayWinners::operator==(const GiveawayWinners&) const = default;
std::strong_ordering GiveawayWinners::operator<=>(const GiveawayWinners&) const = default;
bool GiveawayCompleted::operator==(const GiveawayCompleted&) const = default;
std::strong_ordering GiveawayCompleted::operator<=>(const GiveawayCompleted&) const = default;
bool LinkPreviewOptions::operator==(const LinkPreviewOptions&) const = default;
std::strong_ordering LinkPreviewOptions::operator<=>(const LinkPreviewOptions&) const = default;
bool SuggestedPostPrice::operator==(const SuggestedPostPrice&) const = default;
std::strong_ordering SuggestedPostPrice::operator<=>(const SuggestedPostPrice&) const = default;
bool SuggestedPostInfo::operator==(const SuggestedPostInfo&) const = default;
std::strong_ordering SuggestedPostInfo::operator<=>(const SuggestedPostInfo&) const = default;
bool SuggestedPostParameters::operator==(const SuggestedPostParameters&) const = default;
std::strong_ordering SuggestedPostParameters::operator<=>(const SuggestedPostParameters&) const = default;
bool DirectMessagesTopic::operator==(const DirectMessagesTopic&) const = default;
std::strong_ordering DirectMessagesTopic::operator<=>(const DirectMessagesTopic&) const = default;
bool UserProfilePhotos::operator==(const UserProfilePhotos&) const = default;
std::strong_ordering UserProfilePhotos::operator<=>(const UserProfilePhotos&) const = default;
bool File::operator==(const File&) const = default;
std::strong_ordering File::operator<=>(const File&) const = default;
bool WebAppInfo::operator==(const WebAppInfo&) const = default;
std::strong_ordering WebAppInfo::operator<=>(const WebAppInfo&) const = default;
bool ReplyKeyboardMarkup::operator==(const ReplyKeyboardMarkup&) const = default;
std::strong_ordering ReplyKeyboardMarkup::operator<=>(const ReplyKeyboardMarkup&) const = default;
bool KeyboardButton::operator==(const KeyboardButton&) const = default;
std::strong_ordering KeyboardButton::operator<=>(const KeyboardButton&) const = default;
bool KeyboardButtonRequestUsers::operator==(const KeyboardButtonRequestUsers&) const = default;
std::strong_ordering KeyboardButtonRequestUsers::operator<=>(const KeyboardButtonRequestUsers&) const =
    default;
bool KeyboardButtonRequestChat::operator==(const KeyboardButtonRequestChat&) const = default;
std::strong_ordering KeyboardButtonRequestChat::operator<=>(const KeyboardButtonRequestChat&) const = default;
bool KeyboardButtonPollType::operator==(const KeyboardButtonPollType&) const = default;
std::strong_ordering KeyboardButtonPollType::operator<=>(const KeyboardButtonPollType&) const = default;
bool ReplyKeyboardRemove::operator==(const ReplyKeyboardRemove&) const = default;
std::strong_ordering ReplyKeyboardRemove::operator<=>(const ReplyKeyboardRemove&) const = default;
bool InlineKeyboardMarkup::operator==(const InlineKeyboardMarkup&) const = default;
std::strong_ordering InlineKeyboardMarkup::operator<=>(const InlineKeyboardMarkup&) const = default;
bool InlineKeyboardButton::operator==(const InlineKeyboardButton&) const = default;
std::strong_ordering InlineKeyboardButton::operator<=>(const InlineKeyboardButton&) const = default;
bool LoginUrl::operator==(const LoginUrl&) const = default;
std::strong_ordering LoginUrl::operator<=>(const LoginUrl&) const = default;
bool SwitchInlineQueryChosenChat::operator==(const SwitchInlineQueryChosenChat&) const = default;
std::strong_ordering SwitchInlineQueryChosenChat::operator<=>(const SwitchInlineQueryChosenChat&) const =
    default;
bool CopyTextButton::operator==(const CopyTextButton&) const = default;
std::strong_ordering CopyTextButton::operator<=>(const CopyTextButton&) const = default;
bool CallbackQuery::operator==(const CallbackQuery&) const = default;
std::strong_ordering CallbackQuery::operator<=>(const CallbackQuery&) const = default;
bool ForceReply::operator==(const ForceReply&) const = default;
std::strong_ordering ForceReply::operator<=>(const ForceReply&) const = default;
bool ChatPhoto::operator==(const ChatPhoto&) const = default;
std::strong_ordering ChatPhoto::operator<=>(const ChatPhoto&) const = default;
bool ChatInviteLink::operator==(const ChatInviteLink&) const = default;
std::strong_ordering ChatInviteLink::operator<=>(const ChatInviteLink&) const = default;
bool ChatAdministratorRights::operator==(const ChatAdministratorRights&) const = default;
std::strong_ordering ChatAdministratorRights::operator<=>(const ChatAdministratorRights&) const = default;
bool ChatMemberUpdated::operator==(const ChatMemberUpdated&) const = default;
std::strong_ordering ChatMemberUpdated::operator<=>(const ChatMemberUpdated&) const = default;
bool ChatJoinRequest::operator==(const ChatJoinRequest&) const = default;
std::strong_ordering ChatJoinRequest::operator<=>(const ChatJoinRequest&) const = default;
bool ChatPermissions::operator==(const ChatPermissions&) const = default;
std::strong_ordering ChatPermissions::operator<=>(const ChatPermissions&) const = default;
bool Birthdate::operator==(const Birthdate&) const = default;
std::strong_ordering Birthdate::operator<=>(const Birthdate&) const = default;
bool BusinessIntro::operator==(const BusinessIntro&) const = default;
std::strong_ordering BusinessIntro::operator<=>(const BusinessIntro&) const = default;
bool BusinessLocation::operator==(const BusinessLocation&) const = default;
std::strong_ordering BusinessLocation::operator<=>(const BusinessLocation&) const = default;
bool BusinessOpeningHoursInterval::operator==(const BusinessOpeningHoursInterval&) const = default;
std::strong_ordering BusinessOpeningHoursInterval::operator<=>(const BusinessOpeningHoursInterval&) const =
    default;
bool BusinessOpeningHours::operator==(const BusinessOpeningHours&) const = default;
std::strong_ordering BusinessOpeningHours::operator<=>(const BusinessOpeningHours&) const = default;
bool StoryAreaPosition::operator==(const StoryAreaPosition&) const = default;
std::strong_ordering StoryAreaPosition::operator<=>(const StoryAreaPosition&) const = default;
bool LocationAddress::operator==(const LocationAddress&) const = default;
std::strong_ordering LocationAddress::operator<=>(const LocationAddress&) const = default;
bool StoryArea::operator==(const StoryArea&) const = default;
std::strong_ordering StoryArea::operator<=>(const StoryArea&) const = default;
bool ChatLocation::operator==(const ChatLocation&) const = default;
std::strong_ordering ChatLocation::operator<=>(const ChatLocation&) const = default;
bool ReactionCount::operator==(const ReactionCount&) const = default;
std::strong_ordering ReactionCount::operator<=>(const ReactionCount&) const = default;
bool MessageReactionUpdated::operator==(const MessageReactionUpdated&) const = default;
std::strong_ordering MessageReactionUpdated::operator<=>(const MessageReactionUpdated&) const = default;
bool MessageReactionCountUpdated::operator==(const MessageReactionCountUpdated&) const = default;
std::strong_ordering MessageReactionCountUpdated::operator<=>(const MessageReactionCountUpdated&) const =
    default;
bool ForumTopic::operator==(const ForumTopic&) const = default;
std::strong_ordering ForumTopic::operator<=>(const ForumTopic&) const = default;
bool Gift::operator==(const Gift&) const = default;
std::strong_ordering Gift::operator<=>(const Gift&) const = default;
bool Gifts::operator==(const Gifts&) const = default;
std::strong_ordering Gifts::operator<=>(const Gifts&) const = default;
bool UniqueGiftModel::operator==(const UniqueGiftModel&) const = default;
std::strong_ordering UniqueGiftModel::operator<=>(const UniqueGiftModel&) const = default;
bool UniqueGiftSymbol::operator==(const UniqueGiftSymbol&) const = default;
std::strong_ordering UniqueGiftSymbol::operator<=>(const UniqueGiftSymbol&) const = default;
bool UniqueGiftBackdropColors::operator==(const UniqueGiftBackdropColors&) const = default;
std::strong_ordering UniqueGiftBackdropColors::operator<=>(const UniqueGiftBackdropColors&) const = default;
bool UniqueGiftBackdrop::operator==(const UniqueGiftBackdrop&) const = default;
std::strong_ordering UniqueGiftBackdrop::operator<=>(const UniqueGiftBackdrop&) const = default;
bool UniqueGift::operator==(const UniqueGift&) const = default;
std::strong_ordering UniqueGift::operator<=>(const UniqueGift&) const = default;
bool GiftInfo::operator==(const GiftInfo&) const = default;
std::strong_ordering GiftInfo::operator<=>(const GiftInfo&) const = default;
bool UniqueGiftInfo::operator==(const UniqueGiftInfo&) const = default;
std::strong_ordering UniqueGiftInfo::operator<=>(const UniqueGiftInfo&) const = default;
bool OwnedGifts::operator==(const OwnedGifts&) const = default;
std::strong_ordering OwnedGifts::operator<=>(const OwnedGifts&) const = default;
bool AcceptedGiftTypes::operator==(const AcceptedGiftTypes&) const = default;
std::strong_ordering AcceptedGiftTypes::operator<=>(const AcceptedGiftTypes&) const = default;
bool StarAmount::operator==(const StarAmount&) const = default;
std::strong_ordering StarAmount::operator<=>(const StarAmount&) const = default;
bool BotCommand::operator==(const BotCommand&) const = default;
std::strong_ordering BotCommand::operator<=>(const BotCommand&) const = default;
bool BotName::operator==(const BotName&) const = default;
std::strong_ordering BotName::operator<=>(const BotName&) const = default;
bool BotDescription::operator==(const BotDescription&) const = default;
std::strong_ordering BotDescription::operator<=>(const BotDescription&) const = default;
bool BotShortDescription::operator==(const BotShortDescription&) const = default;
std::strong_ordering BotShortDescription::operator<=>(const BotShortDescription&) const = default;
bool ChatBoost::operator==(const ChatBoost&) const = default;
std::strong_ordering ChatBoost::operator<=>(const ChatBoost&) const = default;
bool ChatBoostUpdated::operator==(const ChatBoostUpdated&) const = default;
std::strong_ordering ChatBoostUpdated::operator<=>(const ChatBoostUpdated&) const = default;
bool ChatBoostRemoved::operator==(const ChatBoostRemoved&) const = default;
std::strong_ordering ChatBoostRemoved::operator<=>(const ChatBoostRemoved&) const = default;
bool UserChatBoosts::operator==(const UserChatBoosts&) const = default;
std::strong_ordering UserChatBoosts::operator<=>(const UserChatBoosts&) const = default;
bool BusinessBotRights::operator==(const BusinessBotRights&) const = default;
std::strong_ordering BusinessBotRights::operator<=>(const BusinessBotRights&) const = default;
bool BusinessConnection::operator==(const BusinessConnection&) const = default;
std::strong_ordering BusinessConnection::operator<=>(const BusinessConnection&) const = default;
bool BusinessMessagesDeleted::operator==(const BusinessMessagesDeleted&) const = default;
std::strong_ordering BusinessMessagesDeleted::operator<=>(const BusinessMessagesDeleted&) const = default;
bool ResponseParameters::operator==(const ResponseParameters&) const = default;
std::strong_ordering ResponseParameters::operator<=>(const ResponseParameters&) const = default;
bool Sticker::operator==(const Sticker&) const = default;
std::strong_ordering Sticker::operator<=>(const Sticker&) const = default;
bool StickerSet::operator==(const StickerSet&) const = default;
std::strong_ordering StickerSet::operator<=>(const StickerSet&) const = default;
bool MaskPosition::operator==(const MaskPosition&) const = default;
std::strong_ordering MaskPosition::operator<=>(const MaskPosition&) const = default;
bool InputSticker::operator==(const InputSticker&) const = default;
std::strong_ordering InputSticker::operator<=>(const InputSticker&) const = default;
bool InlineQuery::operator==(const InlineQuery&) const = default;
std::strong_ordering InlineQuery::operator<=>(const InlineQuery&) const = default;
bool InlineQueryResultsButton::operator==(const InlineQueryResultsButton&) const = default;
std::strong_ordering InlineQueryResultsButton::operator<=>(const InlineQueryResultsButton&) const = default;
bool ChosenInlineResult::operator==(const ChosenInlineResult&) const = default;
std::strong_ordering ChosenInlineResult::operator<=>(const ChosenInlineResult&) const = default;
bool SentWebAppMessage::operator==(const SentWebAppMessage&) const = default;
std::strong_ordering SentWebAppMessage::operator<=>(const SentWebAppMessage&) const = default;
bool PreparedInlineMessage::operator==(const PreparedInlineMessage&) const = default;
std::strong_ordering PreparedInlineMessage::operator<=>(const PreparedInlineMessage&) const = default;
bool LabeledPrice::operator==(const LabeledPrice&) const = default;
std::strong_ordering LabeledPrice::operator<=>(const LabeledPrice&) const = default;
bool Invoice::operator==(const Invoice&) const = default;
std::strong_ordering Invoice::operator<=>(const Invoice&) const = default;
bool ShippingAddress::operator==(const ShippingAddress&) const = default;
std::strong_ordering ShippingAddress::operator<=>(const ShippingAddress&) const = default;
bool OrderInfo::operator==(const OrderInfo&) const = default;
std::strong_ordering OrderInfo::operator<=>(const OrderInfo&) const = default;
bool ShippingOption::operator==(const ShippingOption&) const = default;
std::strong_ordering ShippingOption::operator<=>(const ShippingOption&) const = default;
bool SuccessfulPayment::operator==(const SuccessfulPayment&) const = default;
std::strong_ordering SuccessfulPayment::operator<=>(const SuccessfulPayment&) const = default;
bool RefundedPayment::operator==(const RefundedPayment&) const = default;
std::strong_ordering RefundedPayment::operator<=>(const RefundedPayment&) const = default;
bool ShippingQuery::operator==(const ShippingQuery&) const = default;
std::strong_ordering ShippingQuery::operator<=>(const ShippingQuery&) const = default;
bool PreCheckoutQuery::operator==(const PreCheckoutQuery&) const = default;
std::strong_ordering PreCheckoutQuery::operator<=>(const PreCheckoutQuery&) const = default;
bool PaidMediaPurchased::operator==(const PaidMediaPurchased&) const = default;
std::strong_ordering PaidMediaPurchased::operator<=>(const PaidMediaPurchased&) const = default;
bool AffiliateInfo::operator==(const AffiliateInfo&) const = default;
std::strong_ordering AffiliateInfo::operator<=>(const AffiliateInfo&) const = default;
bool StarTransaction::operator==(const StarTransaction&) const = default;
std::strong_ordering StarTransaction::operator<=>(const StarTransaction&) const = default;
bool StarTransactions::operator==(const StarTransactions&) const = default;
std::strong_ordering StarTransactions::operator<=>(const StarTransactions&) const = default;
bool PassportData::operator==(const PassportData&) const = default;
std::strong_ordering PassportData::operator<=>(const PassportData&) const = default;
bool PassportFile::operator==(const PassportFile&) const = default;
std::strong_ordering PassportFile::operator<=>(const PassportFile&) const = default;
bool EncryptedPassportElement::operator==(const EncryptedPassportElement&) const = default;
std::strong_ordering EncryptedPassportElement::operator<=>(const EncryptedPassportElement&) const = default;
bool EncryptedCredentials::operator==(const EncryptedCredentials&) const = default;
std::strong_ordering EncryptedCredentials::operator<=>(const EncryptedCredentials&) const = default;
bool Game::operator==(const Game&) const = default;
std::strong_ordering Game::operator<=>(const Game&) const = default;
bool CallbackGame::operator==(const CallbackGame&) const = default;
std::strong_ordering CallbackGame::operator<=>(const CallbackGame&) const = default;
bool GameHighScore::operator==(const GameHighScore&) const = default;
std::strong_ordering GameHighScore::operator<=>(const GameHighScore&) const = default;
bool MessageOrigin::operator==(const MessageOrigin&) const = default;
std::strong_ordering MessageOrigin::operator<=>(const MessageOrigin&) const = default;
bool PaidMedia::operator==(const PaidMedia&) const = default;
std::strong_ordering PaidMedia::operator<=>(const PaidMedia&) const = default;
bool BackgroundFill::operator==(const BackgroundFill&) const = default;
std::strong_ordering BackgroundFill::operator<=>(const BackgroundFill&) const = default;
bool BackgroundType::operator==(const BackgroundType&) const = default;
std::strong_ordering BackgroundType::operator<=>(const BackgroundType&) const = default;
bool ChatMember::operator==(const ChatMember&) const = default;
std::strong_ordering ChatMember::operator<=>(const ChatMember&) const = default;
bool StoryAreaType::operator==(const StoryAreaType&) const = default;
std::strong_ordering StoryAreaType::operator<=>(const StoryAreaType&) const = default;
bool ReactionType::operator==(const ReactionType&) const = default;
std::strong_ordering ReactionType::operator<=>(const ReactionType&) const = default;
bool OwnedGift::operator==(const OwnedGift&) const = default;
std::strong_ordering OwnedGift::operator<=>(const OwnedGift&) const = default;
bool BotCommandScope::operator==(const BotCommandScope&) const = default;
std::strong_ordering BotCommandScope::operator<=>(const BotCommandScope&) const = default;
bool MenuButton::operator==(const MenuButton&) const = default;
std::strong_ordering MenuButton::operator<=>(const MenuButton&) const = default;
bool ChatBoostSource::operator==(const ChatBoostSource&) const = default;
std::strong_ordering ChatBoostSource::operator<=>(const ChatBoostSource&) const = default;
bool InputMedia::operator==(const InputMedia&) const = default;
std::strong_ordering InputMedia::operator<=>(const InputMedia&) const = default;
bool InputPaidMedia::operator==(const InputPaidMedia&) const = default;
std::strong_ordering InputPaidMedia::operator<=>(const InputPaidMedia&) const = default;
bool InputProfilePhoto::operator==(const InputProfilePhoto&) const = default;
std::strong_ordering InputProfilePhoto::operator<=>(const InputProfilePhoto&) const = default;
bool InputStoryContent::operator==(const InputStoryContent&) const = default;
std::strong_ordering InputStoryContent::operator<=>(const InputStoryContent&) const = default;
bool InlineQueryResult::operator==(const InlineQueryResult&) const = default;
std::strong_ordering InlineQueryResult::operator<=>(const InlineQueryResult&) const = default;
bool RevenueWithdrawalState::operator==(const RevenueWithdrawalState&) const = default;
std::strong_ordering RevenueWithdrawalState::operator<=>(const RevenueWithdrawalState&) const = default;
bool TransactionPartner::operator==(const TransactionPartner&) const = default;
std::strong_ordering TransactionPartner::operator<=>(const TransactionPartner&) const = default;
bool PassportElementError::operator==(const PassportElementError&) const = default;
std::strong_ordering PassportElementError::operator<=>(const PassportElementError&) const = default;
bool MessageOriginUser::operator==(const MessageOriginUser&) const = default;
std::strong_ordering MessageOriginUser::operator<=>(const MessageOriginUser&) const = default;
bool MessageOriginHiddenUser::operator==(const MessageOriginHiddenUser&) const = default;
std::strong_ordering MessageOriginHiddenUser::operator<=>(const MessageOriginHiddenUser&) const = default;
bool MessageOriginChat::operator==(const MessageOriginChat&) const = default;
std::strong_ordering MessageOriginChat::operator<=>(const MessageOriginChat&) const = default;
bool MessageOriginChannel::operator==(const MessageOriginChannel&) const = default;
std::strong_ordering MessageOriginChannel::operator<=>(const MessageOriginChannel&) const = default;
bool PaidMediaPreview::operator==(const PaidMediaPreview&) const = default;
std::strong_ordering PaidMediaPreview::operator<=>(const PaidMediaPreview&) const = default;
bool PaidMediaPhoto::operator==(const PaidMediaPhoto&) const = default;
std::strong_ordering PaidMediaPhoto::operator<=>(const PaidMediaPhoto&) const = default;
bool PaidMediaVideo::operator==(const PaidMediaVideo&) const = default;
std::strong_ordering PaidMediaVideo::operator<=>(const PaidMediaVideo&) const = default;
bool BackgroundFillSolid::operator==(const BackgroundFillSolid&) const = default;
std::strong_ordering BackgroundFillSolid::operator<=>(const BackgroundFillSolid&) const = default;
bool BackgroundFillGradient::operator==(const BackgroundFillGradient&) const = default;
std::strong_ordering BackgroundFillGradient::operator<=>(const BackgroundFillGradient&) const = default;
bool BackgroundFillFreeformGradient::operator==(const BackgroundFillFreeformGradient&) const = default;
std::strong_ordering BackgroundFillFreeformGradient::operator<=>(
    const BackgroundFillFreeformGradient&) const = default;
bool BackgroundTypeFill::operator==(const BackgroundTypeFill&) const = default;
std::strong_ordering BackgroundTypeFill::operator<=>(const BackgroundTypeFill&) const = default;
bool BackgroundTypeWallpaper::operator==(const BackgroundTypeWallpaper&) const = default;
std::strong_ordering BackgroundTypeWallpaper::operator<=>(const BackgroundTypeWallpaper&) const = default;
bool BackgroundTypePattern::operator==(const BackgroundTypePattern&) const = default;
std::strong_ordering BackgroundTypePattern::operator<=>(const BackgroundTypePattern&) const = default;
bool BackgroundTypeChatTheme::operator==(const BackgroundTypeChatTheme&) const = default;
std::strong_ordering BackgroundTypeChatTheme::operator<=>(const BackgroundTypeChatTheme&) const = default;
bool ChatMemberOwner::operator==(const ChatMemberOwner&) const = default;
std::strong_ordering ChatMemberOwner::operator<=>(const ChatMemberOwner&) const = default;
bool ChatMemberAdministrator::operator==(const ChatMemberAdministrator&) const = default;
std::strong_ordering ChatMemberAdministrator::operator<=>(const ChatMemberAdministrator&) const = default;
bool ChatMemberMember::operator==(const ChatMemberMember&) const = default;
std::strong_ordering ChatMemberMember::operator<=>(const ChatMemberMember&) const = default;
bool ChatMemberRestricted::operator==(const ChatMemberRestricted&) const = default;
std::strong_ordering ChatMemberRestricted::operator<=>(const ChatMemberRestricted&) const = default;
bool ChatMemberLeft::operator==(const ChatMemberLeft&) const = default;
std::strong_ordering ChatMemberLeft::operator<=>(const ChatMemberLeft&) const = default;
bool ChatMemberBanned::operator==(const ChatMemberBanned&) const = default;
std::strong_ordering ChatMemberBanned::operator<=>(const ChatMemberBanned&) const = default;
bool StoryAreaTypeLocation::operator==(const StoryAreaTypeLocation&) const = default;
std::strong_ordering StoryAreaTypeLocation::operator<=>(const StoryAreaTypeLocation&) const = default;
bool StoryAreaTypeSuggestedReaction::operator==(const StoryAreaTypeSuggestedReaction&) const = default;
std::strong_ordering StoryAreaTypeSuggestedReaction::operator<=>(
    const StoryAreaTypeSuggestedReaction&) const = default;
bool StoryAreaTypeLink::operator==(const StoryAreaTypeLink&) const = default;
std::strong_ordering StoryAreaTypeLink::operator<=>(const StoryAreaTypeLink&) const = default;
bool StoryAreaTypeWeather::operator==(const StoryAreaTypeWeather&) const = default;
std::strong_ordering StoryAreaTypeWeather::operator<=>(const StoryAreaTypeWeather&) const = default;
bool StoryAreaTypeUniqueGift::operator==(const StoryAreaTypeUniqueGift&) const = default;
std::strong_ordering StoryAreaTypeUniqueGift::operator<=>(const StoryAreaTypeUniqueGift&) const = default;
bool ReactionTypeEmoji::operator==(const ReactionTypeEmoji&) const = default;
std::strong_ordering ReactionTypeEmoji::operator<=>(const ReactionTypeEmoji&) const = default;
bool ReactionTypeCustomEmoji::operator==(const ReactionTypeCustomEmoji&) const = default;
std::strong_ordering ReactionTypeCustomEmoji::operator<=>(const ReactionTypeCustomEmoji&) const = default;
bool ReactionTypePaid::operator==(const ReactionTypePaid&) const = default;
std::strong_ordering ReactionTypePaid::operator<=>(const ReactionTypePaid&) const = default;
bool OwnedGiftRegular::operator==(const OwnedGiftRegular&) const = default;
std::strong_ordering OwnedGiftRegular::operator<=>(const OwnedGiftRegular&) const = default;
bool OwnedGiftUnique::operator==(const OwnedGiftUnique&) const = default;
std::strong_ordering OwnedGiftUnique::operator<=>(const OwnedGiftUnique&) const = default;
bool BotCommandScopeDefault::operator==(const BotCommandScopeDefault&) const = default;
std::strong_ordering BotCommandScopeDefault::operator<=>(const BotCommandScopeDefault&) const = default;
bool BotCommandScopeAllPrivateChats::operator==(const BotCommandScopeAllPrivateChats&) const = default;
std::strong_ordering BotCommandScopeAllPrivateChats::operator<=>(
    const BotCommandScopeAllPrivateChats&) const = default;
bool BotCommandScopeAllGroupChats::operator==(const BotCommandScopeAllGroupChats&) const = default;
std::strong_ordering BotCommandScopeAllGroupChats::operator<=>(const BotCommandScopeAllGroupChats&) const =
    default;
bool BotCommandScopeAllChatAdministrators::operator==(const BotCommandScopeAllChatAdministrators&) const =
    default;
std::strong_ordering BotCommandScopeAllChatAdministrators::operator<=>(
    const BotCommandScopeAllChatAdministrators&) const = default;
bool BotCommandScopeChat::operator==(const BotCommandScopeChat&) const = default;
std::strong_ordering BotCommandScopeChat::operator<=>(const BotCommandScopeChat&) const = default;
bool BotCommandScopeChatAdministrators::operator==(const BotCommandScopeChatAdministrators&) const = default;
std::strong_ordering BotCommandScopeChatAdministrators::operator<=>(
    const BotCommandScopeChatAdministrators&) const = default;
bool BotCommandScopeChatMember::operator==(const BotCommandScopeChatMember&) const = default;
std::strong_ordering BotCommandScopeChatMember::operator<=>(const BotCommandScopeChatMember&) const = default;
bool MenuButtonCommands::operator==(const MenuButtonCommands&) const = default;
std::strong_ordering MenuButtonCommands::operator<=>(const MenuButtonCommands&) const = default;
bool MenuButtonWebApp::operator==(const MenuButtonWebApp&) const = default;
std::strong_ordering MenuButtonWebApp::operator<=>(const MenuButtonWebApp&) const = default;
bool MenuButtonDefault::operator==(const MenuButtonDefault&) const = default;
std::strong_ordering MenuButtonDefault::operator<=>(const MenuButtonDefault&) const = default;
bool ChatBoostSourcePremium::operator==(const ChatBoostSourcePremium&) const = default;
std::strong_ordering ChatBoostSourcePremium::operator<=>(const ChatBoostSourcePremium&) const = default;
bool ChatBoostSourceGiftCode::operator==(const ChatBoostSourceGiftCode&) const = default;
std::strong_ordering ChatBoostSourceGiftCode::operator<=>(const ChatBoostSourceGiftCode&) const = default;
bool ChatBoostSourceGiveaway::operator==(const ChatBoostSourceGiveaway&) const = default;
std::strong_ordering ChatBoostSourceGiveaway::operator<=>(const ChatBoostSourceGiveaway&) const = default;
bool InputMediaAnimation::operator==(const InputMediaAnimation&) const = default;
std::strong_ordering InputMediaAnimation::operator<=>(const InputMediaAnimation&) const = default;
bool InputMediaDocument::operator==(const InputMediaDocument&) const = default;
std::strong_ordering InputMediaDocument::operator<=>(const InputMediaDocument&) const = default;
bool InputMediaAudio::operator==(const InputMediaAudio&) const = default;
std::strong_ordering InputMediaAudio::operator<=>(const InputMediaAudio&) const = default;
bool InputMediaPhoto::operator==(const InputMediaPhoto&) const = default;
std::strong_ordering InputMediaPhoto::operator<=>(const InputMediaPhoto&) const = default;
bool InputMediaVideo::operator==(const InputMediaVideo&) const = default;
std::strong_ordering InputMediaVideo::operator<=>(const InputMediaVideo&) const = default;
bool InputPaidMediaPhoto::operator==(const InputPaidMediaPhoto&) const = default;
std::strong_ordering InputPaidMediaPhoto::operator<=>(const InputPaidMediaPhoto&) const = default;
bool InputPaidMediaVideo::operator==(const InputPaidMediaVideo&) const = default;
std::strong_ordering InputPaidMediaVideo::operator<=>(const InputPaidMediaVideo&) const = default;
bool InputProfilePhotoStatic::operator==(const InputProfilePhotoStatic&) const = default;
std::strong_ordering InputProfilePhotoStatic::operator<=>(const InputProfilePhotoStatic&) const = default;
bool InputProfilePhotoAnimated::operator==(const InputProfilePhotoAnimated&) const = default;
std::strong_ordering InputProfilePhotoAnimated::operator<=>(const InputProfilePhotoAnimated&) const = default;
bool InputStoryContentPhoto::operator==(const InputStoryContentPhoto&) const = default;
std::strong_ordering InputStoryContentPhoto::operator<=>(const InputStoryContentPhoto&) const = default;
bool InputStoryContentVideo::operator==(const InputStoryContentVideo&) const = default;
std::strong_ordering InputStoryContentVideo::operator<=>(const InputStoryContentVideo&) const = default;
bool InlineQueryResultCachedAudio::operator==(const InlineQueryResultCachedAudio&) const = default;
std::strong_ordering InlineQueryResultCachedAudio::operator<=>(const InlineQueryResultCachedAudio&) const =
    default;
bool InlineQueryResultCachedDocument::operator==(const InlineQueryResultCachedDocument&) const = default;
std::strong_ordering InlineQueryResultCachedDocument::operator<=>(
    const InlineQueryResultCachedDocument&) const = default;
bool InlineQueryResultCachedGif::operator==(const InlineQueryResultCachedGif&) const = default;
std::strong_ordering InlineQueryResultCachedGif::operator<=>(const InlineQueryResultCachedGif&) const =
    default;
bool InlineQueryResultCachedMpeg4Gif::operator==(const InlineQueryResultCachedMpeg4Gif&) const = default;
std::strong_ordering InlineQueryResultCachedMpeg4Gif::operator<=>(
    const InlineQueryResultCachedMpeg4Gif&) const = default;
bool InlineQueryResultCachedPhoto::operator==(const InlineQueryResultCachedPhoto&) const = default;
std::strong_ordering InlineQueryResultCachedPhoto::operator<=>(const InlineQueryResultCachedPhoto&) const =
    default;
bool InlineQueryResultCachedSticker::operator==(const InlineQueryResultCachedSticker&) const = default;
std::strong_ordering InlineQueryResultCachedSticker::operator<=>(
    const InlineQueryResultCachedSticker&) const = default;
bool InlineQueryResultCachedVideo::operator==(const InlineQueryResultCachedVideo&) const = default;
std::strong_ordering InlineQueryResultCachedVideo::operator<=>(const InlineQueryResultCachedVideo&) const =
    default;
bool InlineQueryResultCachedVoice::operator==(const InlineQueryResultCachedVoice&) const = default;
std::strong_ordering InlineQueryResultCachedVoice::operator<=>(const InlineQueryResultCachedVoice&) const =
    default;
bool InlineQueryResultArticle::operator==(const InlineQueryResultArticle&) const = default;
std::strong_ordering InlineQueryResultArticle::operator<=>(const InlineQueryResultArticle&) const = default;
bool InlineQueryResultAudio::operator==(const InlineQueryResultAudio&) const = default;
std::strong_ordering InlineQueryResultAudio::operator<=>(const InlineQueryResultAudio&) const = default;
bool InlineQueryResultContact::operator==(const InlineQueryResultContact&) const = default;
std::strong_ordering InlineQueryResultContact::operator<=>(const InlineQueryResultContact&) const = default;
bool InlineQueryResultGame::operator==(const InlineQueryResultGame&) const = default;
std::strong_ordering InlineQueryResultGame::operator<=>(const InlineQueryResultGame&) const = default;
bool InlineQueryResultDocument::operator==(const InlineQueryResultDocument&) const = default;
std::strong_ordering InlineQueryResultDocument::operator<=>(const InlineQueryResultDocument&) const = default;
bool InlineQueryResultGif::operator==(const InlineQueryResultGif&) const = default;
std::strong_ordering InlineQueryResultGif::operator<=>(const InlineQueryResultGif&) const = default;
bool InlineQueryResultLocation::operator==(const InlineQueryResultLocation&) const = default;
std::strong_ordering InlineQueryResultLocation::operator<=>(const InlineQueryResultLocation&) const = default;
bool InlineQueryResultMpeg4Gif::operator==(const InlineQueryResultMpeg4Gif&) const = default;
std::strong_ordering InlineQueryResultMpeg4Gif::operator<=>(const InlineQueryResultMpeg4Gif&) const = default;
bool InlineQueryResultPhoto::operator==(const InlineQueryResultPhoto&) const = default;
std::strong_ordering InlineQueryResultPhoto::operator<=>(const InlineQueryResultPhoto&) const = default;
bool InlineQueryResultVenue::operator==(const InlineQueryResultVenue&) const = default;
std::strong_ordering InlineQueryResultVenue::operator<=>(const InlineQueryResultVenue&) const = default;
bool InlineQueryResultVideo::operator==(const InlineQueryResultVideo&) const = default;
std::strong_ordering InlineQueryResultVideo::operator<=>(const InlineQueryResultVideo&) const = default;
bool InlineQueryResultVoice::operator==(const InlineQueryResultVoice&) const = default;
std::strong_ordering InlineQueryResultVoice::operator<=>(const InlineQueryResultVoice&) const = default;
bool InputTextMessageContent::operator==(const InputTextMessageContent&) const = default;
std::strong_ordering InputTextMessageContent::operator<=>(const InputTextMessageContent&) const = default;
bool InputLocationMessageContent::operator==(const InputLocationMessageContent&) const = default;
std::strong_ordering InputLocationMessageContent::operator<=>(const InputLocationMessageContent&) const =
    default;
bool InputVenueMessageContent::operator==(const InputVenueMessageContent&) const = default;
std::strong_ordering InputVenueMessageContent::operator<=>(const InputVenueMessageContent&) const = default;
bool InputContactMessageContent::operator==(const InputContactMessageContent&) const = default;
std::strong_ordering InputContactMessageContent::operator<=>(const InputContactMessageContent&) const =
    default;
bool InputInvoiceMessageContent::operator==(const InputInvoiceMessageContent&) const = default;
std::strong_ordering InputInvoiceMessageContent::operator<=>(const InputInvoiceMessageContent&) const =
    default;
bool RevenueWithdrawalStatePending::operator==(const RevenueWithdrawalStatePending&) const = default;
std::strong_ordering RevenueWithdrawalStatePending::operator<=>(const RevenueWithdrawalStatePending&) const =
    default;
bool RevenueWithdrawalStateSucceeded::operator==(const RevenueWithdrawalStateSucceeded&) const = default;
std::strong_ordering RevenueWithdrawalStateSucceeded::operator<=>(
    const RevenueWithdrawalStateSucceeded&) const = default;
bool RevenueWithdrawalStateFailed::operator==(const RevenueWithdrawalStateFailed&) const = default;
std::strong_ordering RevenueWithdrawalStateFailed::operator<=>(const RevenueWithdrawalStateFailed&) const =
    default;
bool TransactionPartnerUser::operator==(const TransactionPartnerUser&) const = default;
std::strong_ordering TransactionPartnerUser::operator<=>(const TransactionPartnerUser&) const = default;
bool TransactionPartnerChat::operator==(const TransactionPartnerChat&) const = default;
std::strong_ordering TransactionPartnerChat::operator<=>(const TransactionPartnerChat&) const = default;
bool TransactionPartnerAffiliateProgram::operator==(const TransactionPartnerAffiliateProgram&) const =
    default;
std::strong_ordering TransactionPartnerAffiliateProgram::operator<=>(
    const TransactionPartnerAffiliateProgram&) const = default;
bool TransactionPartnerFragment::operator==(const TransactionPartnerFragment&) const = default;
std::strong_ordering TransactionPartnerFragment::operator<=>(const TransactionPartnerFragment&) const =
    default;
bool TransactionPartnerTelegramAds::operator==(const TransactionPartnerTelegramAds&) const = default;
std::strong_ordering TransactionPartnerTelegramAds::operator<=>(const TransactionPartnerTelegramAds&) const =
    default;
bool TransactionPartnerTelegramApi::operator==(const TransactionPartnerTelegramApi&) const = default;
std::strong_ordering TransactionPartnerTelegramApi::operator<=>(const TransactionPartnerTelegramApi&) const =
    default;
bool TransactionPartnerOther::operator==(const TransactionPartnerOther&) const = default;
std::strong_ordering TransactionPartnerOther::operator<=>(const TransactionPartnerOther&) const = default;
bool PassportElementErrorDataField::operator==(const PassportElementErrorDataField&) const = default;
std::strong_ordering PassportElementErrorDataField::operator<=>(const PassportElementErrorDataField&) const =
    default;
bool PassportElementErrorFrontSide::operator==(const PassportElementErrorFrontSide&) const = default;
std::strong_ordering PassportElementErrorFrontSide::operator<=>(const PassportElementErrorFrontSide&) const =
    default;
bool PassportElementErrorReverseSide::operator==(const PassportElementErrorReverseSide&) const = default;
std::strong_ordering PassportElementErrorReverseSide::operator<=>(
    const PassportElementErrorReverseSide&) const = default;
bool PassportElementErrorSelfie::operator==(const PassportElementErrorSelfie&) const = default;
std::strong_ordering PassportElementErrorSelfie::operator<=>(const PassportElementErrorSelfie&) const =
    default;
bool PassportElementErrorFile::operator==(const PassportElementErrorFile&) const = default;
std::strong_ordering PassportElementErrorFile::operator<=>(const PassportElementErrorFile&) const = default;
bool PassportElementErrorFiles::operator==(const PassportElementErrorFiles&) const = default;
std::strong_ordering PassportElementErrorFiles::operator<=>(const PassportElementErrorFiles&) const = default;
bool PassportElementErrorTranslationFile::operator==(const PassportElementErrorTranslationFile&) const =
    default;
std::strong_ordering PassportElementErrorTranslationFile::operator<=>(
    const PassportElementErrorTranslationFile&) const = default;
bool PassportElementErrorTranslationFiles::operator==(const PassportElementErrorTranslationFiles&) const =
    default;
std::strong_ordering PassportElementErrorTranslationFiles::operator<=>(
    const PassportElementErrorTranslationFiles&) const = default;
bool PassportElementErrorUnspecified::operator==(const PassportElementErrorUnspecified&) const = default;
std::strong_ordering PassportElementErrorUnspecified::operator<=>(
    const PassportElementErrorUnspecified&) const = default;
}  // namespace tgbm::api
