name: format_check

permissions:
  actions: write
  contents: read

'on':
  pull_request:
  push:
    branches:
      - master

env:
  UBSAN_OPTIONS: print_stacktrace=1

jobs:
  format_check:
    strategy:
      fail-fast: false

    name: 'format_check'
    runs-on: ubuntu-24.04

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo make -f scripts/ci_ubuntu.make install-compiler compiler=clang version=19
      - name: Format
        run: >
          sudo make 
          -f scripts/ci_ubuntu.make 
          format

      - name: Check if all files are committed to git
        run: >
          sudo make 
          -f scripts/ci_ubuntu.make 
          check-git-status
